language: c++

os:
  - linux
  - osx

dist:
  - bionic

osx_image:
  - xcode11.3

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=RELEASE

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - ci/before_install.sh

install:
  - ci/install.sh

script:
  - ci/build.sh && ci/test.sh
