language: c++

cache:
  ccache: true
  pip: true
  directories:
    - $HOME/.hunter

addons:
  apt:
    packages:
      - libgflags-dev
      - python3
      - python3-pip
      - python3-setuptools
      - libsnappy-dev
      - zlib1g-dev
      - libbz2-dev
      - liblz4-dev
      - libzstd-dev
    update: true

jobs:
  include:
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=coverage
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - os: linux
      dist: bionic
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
  eval "${MATRIX_EVAL}"

install:
  - ci/install.sh

script:
  - ci/build.sh && ci/test.sh

after_success:
  - ci/after_success.sh

notifications:
  slack:
    secure: HYp3mDmCvtrCBjmw+jH4XGVHpYxOZ6O7jXFOM6/QyNDGKZoQaAKr4ZvArtsr5FcnwDi9eVaEyKDwtNpZiUxtFYLO7icejqtW0ibbmDwUTHBAln3vjJnBAwqu0RgloRMLgunJ1M91wnszUoPxSCfeR4xVUtnVl0HbQTaqHc0Z01OBUS1DB9NI+hbb/IkOADBCF7D4T3PubjcWLHdhqGyBtIuwVQ3PEwEMq/4FrGScJnVAp1mDNW2C0StbIJGPetpxCEAIFOsGfdAHF7eNJSkPn6xsjcDlXTp9QX2XgVPOTUILFDn5Eddi+TZM3BMx3keG+vTL6tfLr4d/da13HwcvPbYlowVAfvwV/OsEYskRJ8qNERKg/VAi8m4xdFq8AeE2XLSM8kZyiLb9ki2Ifv+t/Tvp2tZ8qCZlbgsTdCTdILKAKWka0tNwPPDLfG3mHYbFZE4K8rRUTDI2e7b39UpbTRA1qNcrqkP8oQRuvORcKan8JohPPWjuf+XCaP2eteEjyqu60MkhCQ+CSpcocyz4ROLKwAYA2FVhqhIFIxB6fpwivVGxgl/OM1LIcMQEnrDIcZxyaaiICMQHFCBqNLOhI6lOr6XSnJaz0bDK/jFM89vm9vSFlYQ/pMYVE8prfjaXR9ITkC5eOTZMaYnX8sIemK1MC+hpyMnCHsY5fB1HW/A=
    on_success: never
